### ISSUE TITLE
Rust In Ecocode

### ISSUE THREAD

**Issue by Jberque** [green-code-initiative/website#3]
In "Contributeur" page, there is a Rust logo

Are you sure an Ecocode Rust plugin exists ?

**Comment by dedece35** [comment]
Hi @Jberque, (@glalloue, @mdubois81 )

there is no implemented RUST plugin, you're rigth.
but there are several rules ideas for RUST.
Thus for me, RUST is here but not implementation for now, because of no RUST experts.
But, once an RUST expect will be ok to do implementation, I will support him to initiate the plugin.
Indeed, I can now initita ethie plugin if we are ok with this, like I made with HTML plugin (there is no implementation inside, but plugin is inititated)

what do you think about it @glalloue, @mdubois81 ?

**Comment by jhertout** [comment]
Hi,

@dedece35 what do you mean by "initiate the plugin"? I do not know if it is a good idea to have "empty" plugins in the repo, in the middle of the other projects. It is only my opinion but for users that come to see our work, it can be frustrating to see "empty" projects. And for us, if we begin to initialize all the projects where we only have ideas, it will be difficult to find the repo where we have "active" work in the middle of all of this.

We can discuss, it is only my opinion!

**Comment by dedece35** [comment]
@jhertout, no problem, I'm ok with you.
I initiated an empty HTML plugin because of different discussions with @utarwyn and @MP-Aubay. Some HTML rules could be implemented in this plugin.
For RUST, there is no RUST expert for now, I agree with you to initiate empty plugin RUST once this expert will join us.

**Comment by mdubois81** [comment]
I agree with that conclusion. I also think that it is a good idea to keep the reference to RUST on the website. It is a good way to catch the interest of RUST experts that could fall on it ;)

**Comment by Jberque** [comment]
OK So I close the issue.
